# RFC 9457 Problem Details
# Shared error response schema
openapi: 3.0.3
info:
  title: Problem Details
  version: 1.0.0

components:
  schemas:
    ProblemDetails:
      type: object
      description: RFC 9457 Problem Details for HTTP APIs
      required:
        - type
        - title
        - status
      properties:
        type:
          type: string
          format: uri-reference
          description: A URI reference that identifies the problem type
          example: /errors/validation
        title:
          type: string
          description: A short, human-readable summary
          example: Validation Error
        status:
          type: integer
          description: The HTTP status code
          example: 400
        detail:
          type: string
          description: A human-readable explanation specific to this occurrence
          example: The email field is invalid
        instance:
          type: string
          format: uri
          description: A URI reference to the specific occurrence
        code:
          type: string
          description: Application-specific error code (SCREAMING_SNAKE_CASE)
          example: VALIDATION_FAILED
        traceId:
          type: string
          description: Request trace ID for debugging
        errors:
          type: array
          description: Detailed validation errors
          items:
            $ref: '#/components/schemas/ValidationError'

    ValidationError:
      type: object
      required:
        - pointer
        - detail
      properties:
        pointer:
          type: string
          description: JSON Pointer to the invalid field
          example: /email
        detail:
          type: string
          description: Error message for this field
          example: Must be a valid email address

  responses:
    BadRequest:
      description: Bad Request
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/ProblemDetails'

    Unauthorized:
      description: Unauthorized
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/ProblemDetails'

    Forbidden:
      description: Forbidden
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/ProblemDetails'

    NotFound:
      description: Not Found
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/ProblemDetails'

    TooManyRequests:
      description: Too Many Requests
      headers:
        Retry-After:
          schema:
            type: integer
          description: Seconds until rate limit resets
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/ProblemDetails'

    InternalError:
      description: Internal Server Error
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/ProblemDetails'

